# Generated by Django 3.2.8 on 2021-10-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movie_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(blank=True, null=True, to='core.Movie'),
        ),
    ]
