# Generated by Django 3.2.8 on 2021-10-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_actor_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
