# Generated by Django 3.2.8 on 2021-11-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_director_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermovie',
            name='rating',
            field=models.FloatField(max_length=5),
        ),
    ]
