# Generated by Django 3.2.8 on 2021-11-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211103_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovie',
            name='bought',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
